dist: bionic

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install numpy
  - pip install git+https://github.com/rmjarvis/MockMPI@exec-args

cache: pip

script:
  - export PYTHONPATH=$PWD:$PYTHONPATH
  - pytest
